using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CopaEditor.Utils
{
    class stringToHexaJIS
    {
        public static String convertCara(String s)
        {

            switch (s)
            {
                case " ":
                    return "20";
                case "!":
                    return "21";
                case "\"":
                    return "22";
                case "Ö":
                    return "0A";
                case "#":
                    return "23";
                case "$":
                    return "24";
                case "%":
                    return "25";
                case "&":
                    return "26";
                case "'":
                    return "27";
                case "(":
                    return "28";
                case ")":
                    return "29";
                case "*":
                    return "2A";
                case "+":
                    return "2B";
                case ",":
                    return "2C";
                case "-":
                    return "2D";
                case ".":
                    return "2E";
                case "/":
                    return "2F";
                case "0":
                    return "30";
                case "1":
                    return "31";
                case "2":
                    return "32";
                case "3":
                    return "33";
                case "4":
                    return "34";
                case "5":
                    return "35";
                case "6":
                    return "36";
                case "7":
                    return "37";
                case "8":
                    return "38";
                case "9":
                    return "39";
                case ":":
                    return "3A";
                case ";":
                    return "3B";
                case "<":
                    return "3C";
                case "=":
                    return "3D";
                case ">":
                    return "3E";
                case "?":
                    return "3F";
                case "@":
                    return "40";
                case "A":
                    return "41";
                case "B":
                    return "42";
                case "C":
                    return "43";
                case "D":
                    return "44";
                case "E":
                    return "45";
                case "F":
                    return "46";
                case "G":
                    return "47";
                case "H":
                    return "48";
                case "I":
                    return "49";
                case "J":
                    return "4A";
                case "K":
                    return "4B";
                case "L":
                    return "4C";
                case "M":
                    return "4D";
                case "N":
                    return "4E";
                case "O":
                    return "4F";
                case "P":
                    return "50";
                case "Q":
                    return "51";
                case "R":
                    return "52";
                case "S":
                    return "53";
                case "T":
                    return "54";
                case "U":
                    return "55";
                case "V":
                    return "56";
                case "W":
                    return "57";
                case "X":
                    return "58";
                case "Y":
                    return "59";
                case "Z":
                    return "5A";
                case "[":
                    return "5B";
                case "¥":
                    return "5C";
                case "]":
                    return "5D";
                case "^":
                    return "5E";
                case "_":
                    return "5F";
                case "`":
                    return "60";
                case "a":
                    return "61";
                case "b":
                    return "62";
                case "c":
                    return "63";
                case "d":
                    return "64";
                case "e":
                    return "65";
                case "f":
                    return "66";
                case "g":
                    return "67";
                case "h":
                    return "68";
                case "i":
                    return "69";
                case "j":
                    return "6A";
                case "k":
                    return "6B";
                case "l":
                    return "6C";
                case "m":
                    return "6D";
                case "n":
                    return "6E";
                case "o":
                    return "6F";
                case "p":
                    return "70";
                case "q":
                    return "71";
                case "r":
                    return "72";
                case "s":
                    return "73";
                case "t":
                    return "74";
                case "u":
                    return "75";
                case "v":
                    return "76";
                case "w":
                    return "77";
                case "x":
                    return "78";
                case "y":
                    return "79";
                case "z":
                    return "7A";
                case "{":
                    return "7B";
                case "|":
                    return "7C";
                case "}":
                    return "7D";
                case "‾":
                    return "7E";
                case "、":
                    return "8141";
                case "。":
                    return "8142";
                case "…":
                    return "8163";
                case "？":
                    return "8148";
                case "・":
                    return "8145";
                case "ー":
                    return "815B";
                case "！":
                    return "8149";
                case "「":
                    return "8175";
                case "」":
                    return "8176";
                case "０":
                    return "824F";
                case "１":
                    return "8250";
                case "２":
                    return "8251";
                case "３":
                    return "8252";
                case "４":
                    return "8253";
                case "５":
                    return "8254";
                case "６":
                    return "8255";
                case "７":
                    return "8256";
                case "８":
                    return "8257";
                case "９":
                    return "8258";
                case "Ａ":
                    return "8260";
                case "Ｂ":
                    return "8261";
                case "Ｃ":
                    return "8262";
                case "Ｄ":
                    return "8263";
                case "Ｅ":
                    return "8264";
                case "Ｆ":
                    return "8265";
                case "Ｇ":
                    return "8266";
                case "Ｈ":
                    return "8267";
                case "Ｉ":
                    return "8268";
                case "Ｊ":
                    return "8269";
                case "Ｋ":
                    return "826A";
                case "Ｌ":
                    return "826B";
                case "Ｍ":
                    return "826C";
                case "Ｎ":
                    return "826D";
                case "Ｏ":
                    return "826E";
                case "Ｐ":
                    return "826F";
                case "Ｑ":
                    return "8270";
                case "Ｒ":
                    return "8271";
                case "Ｓ":
                    return "8272";
                case "Ｔ":
                    return "8273";
                case "Ｕ":
                    return "8274";
                case "Ｖ":
                    return "8275";
                case "Ｗ":
                    return "8276";
                case "Ｘ":
                    return "8277";
                case "Ｙ":
                    return "8278";
                case "Ｚ":
                    return "8279";
                case "ａ":
                    return "8281";
                case "ｂ":
                    return "8282";
                case "ｃ":
                    return "8283";
                case "ｄ":
                    return "8284";
                case "ｅ":
                    return "8285";
                case "ｆ":
                    return "8286";
                case "ｇ":
                    return "8287";
                case "ｈ":
                    return "8288";
                case "ｉ":
                    return "8289";
                case "ｊ":
                    return "828A";
                case "ｋ":
                    return "828B";
                case "ｌ":
                    return "828C";
                case "ｍ":
                    return "828D";
                case "ｎ":
                    return "828E";
                case "ｏ":
                    return "828F";
                case "ｐ":
                    return "8290";
                case "ｑ":
                    return "8291";
                case "ｒ":
                    return "8292";
                case "ｓ":
                    return "8293";
                case "ｔ":
                    return "8294";
                case "ｕ":
                    return "8295";
                case "ｖ":
                    return "8296";
                case "ｗ":
                    return "8297";
                case "ｘ":
                    return "8298";
                case "ｙ":
                    return "8299";
                case "ｚ":
                    return "829A";
                case "ぁ":
                    return "829F";
                case "あ":
                    return "82A0";
                case "ぃ":
                    return "82A1";
                case "い":
                    return "82A2";
                case "ぅ":
                    return "82A3";
                case "う":
                    return "82A4";
                case "ぇ":
                    return "82A5";
                case "え":
                    return "82A6";
                case "ぉ":
                    return "82A7";
                case "お":
                    return "82A8";
                case "か":
                    return "82A9";
                case "が":
                    return "82AA";
                case "き":
                    return "82AB";
                case "ぎ":
                    return "82AC";
                case "く":
                    return "82AD";
                case "ぐ":
                    return "82AE";
                case "け":
                    return "82AF";
                case "げ":
                    return "82B0";
                case "こ":
                    return "82B1";
                case "ご":
                    return "82B2";
                case "さ":
                    return "82B3";
                case "ざ":
                    return "82B4";
                case "し":
                    return "82B5";
                case "じ":
                    return "82B6";
                case "す":
                    return "82B7";
                case "ず":
                    return "82B8";
                case "せ":
                    return "82B9";
                case "ぜ":
                    return "82BA";
                case "そ":
                    return "82BB";
                case "ぞ":
                    return "82BC";
                case "た":
                    return "82BD";
                case "だ":
                    return "82BE";
                case "ち":
                    return "82BF";
                case "ぢ":
                    return "82C0";
                case "っ":
                    return "82C1";
                case "つ":
                    return "82C2";
                case "づ":
                    return "82C3";
                case "て":
                    return "82C4";
                case "で":
                    return "82C5";
                case "と":
                    return "82C6";
                case "ど":
                    return "82C7";
                case "な":
                    return "82C8";
                case "に":
                    return "82C9";
                case "ぬ":
                    return "82CA";
                case "ね":
                    return "82CB";
                case "の":
                    return "82CC";
                case "は":
                    return "82CD";
                case "ば":
                    return "82CE";
                case "ぱ":
                    return "82CF";
                case "ひ":
                    return "82D0";
                case "び":
                    return "82D1";
                case "ぴ":
                    return "82D2";
                case "ふ":
                    return "82D3";
                case "ぶ":
                    return "82D4";
                case "ぷ":
                    return "82D5";
                case "へ":
                    return "82D6";
                case "べ":
                    return "82D7";
                case "ぺ":
                    return "82D8";
                case "ほ":
                    return "82D9";
                case "ぼ":
                    return "82DA";
                case "ぽ":
                    return "82DB";
                case "ま":
                    return "82DC";
                case "み":
                    return "82DD";
                case "む":
                    return "82DE";
                case "め":
                    return "82DF";
                case "も":
                    return "82E0";
                case "ゃ":
                    return "82E1";
                case "や":
                    return "82E2";
                case "ゅ":
                    return "82E3";
                case "ゆ":
                    return "82E4";
                case "ょ":
                    return "82E5";
                case "よ":
                    return "82E6";
                case "ら":
                    return "82E7";
                case "り":
                    return "82E8";
                case "る":
                    return "82E9";
                case "れ":
                    return "82EA";
                case "ろ":
                    return "82EB";
                case "ゎ":
                    return "82EC";
                case "わ":
                    return "82ED";
                case "ゐ":
                    return "82EE";
                case "ゑ":
                    return "82EF";
                case "を":
                    return "82F0";
                case "ん":
                    return "82F1";
                case "ァ":
                    return "8340";
                case "ア":
                    return "8341";
                case "ィ":
                    return "8342";
                case "イ":
                    return "8343";
                case "ゥ":
                    return "8344";
                case "ウ":
                    return "8345";
                case "ェ":
                    return "8346";
                case "エ":
                    return "8347";
                case "ォ":
                    return "8348";
                case "オ":
                    return "8349";
                case "カ":
                    return "834A";
                case "ガ":
                    return "834B";
                case "キ":
                    return "834C";
                case "ギ":
                    return "834D";
                case "ク":
                    return "834E";
                case "グ":
                    return "834F";
                case "ケ":
                    return "8350";
                case "ゲ":
                    return "8351";
                case "コ":
                    return "8352";
                case "ゴ":
                    return "8353";
                case "サ":
                    return "8354";
                case "ザ":
                    return "8355";
                case "シ":
                    return "8356";
                case "ジ":
                    return "8357";
                case "ス":
                    return "8358";
                case "ズ":
                    return "8359";
                case "セ":
                    return "835A";
                case "ソ":
                    return "835C";
                case "ゾ":
                    return "835D";
                case "タ":
                    return "835E";
                case "ダ":
                    return "835F";
                case "チ":
                    return "8360";
                case "ヂ":
                    return "8361";
                case "ッ":
                    return "8362";
                case "ツ":
                    return "8363";
                case "ヅ":
                    return "8364";
                case "テ":
                    return "8365";
                case "デ":
                    return "8366";
                case "ト":
                    return "8367";
                case "ド":
                    return "8368";
                case "ナ":
                    return "8369";
                case "ニ":
                    return "836A";
                case "ヌ":
                    return "836B";
                case "ネ":
                    return "836C";
                case "ノ":
                    return "836D";
                case "ハ":
                    return "836E";
                case "バ":
                    return "836F";
                case "パ":
                    return "8370";
                case "ヒ":
                    return "8371";
                case "ビ":
                    return "8372";
                case "ピ":
                    return "8373";
                case "フ":
                    return "8374";
                case "ブ":
                    return "8375";
                case "プ":
                    return "8376";
                case "ヘ":
                    return "8377";
                case "ベ":
                    return "8378";
                case "ペ":
                    return "8379";
                case "ホ":
                    return "837A";
                case "ボ":
                    return "837B";
                case "ポ":
                    return "837C";
                case "マ":
                    return "837D";
                case "ミ":
                    return "837E";
                case "ム":
                    return "8380";
                case "メ":
                    return "8381";
                case "モ":
                    return "8382";
                case "ャ":
                    return "8383";
                case "ヤ":
                    return "8384";
                case "ュ":
                    return "8385";
                case "ユ":
                    return "8386";
                case "ョ":
                    return "8387";
                case "ヨ":
                    return "8388";
                case "ラ":
                    return "8389";
                case "リ":
                    return "838A";
                case "ル":
                    return "838B";
                case "レ":
                    return "838C";
                case "ロ":
                    return "838D";
                case "ヮ":
                    return "838E";
                case "ワ":
                    return "838F";
                case "ヰ":
                    return "8390";
                case "ヱ":
                    return "8391";
                case "ヲ":
                    return "8392";
                case "ン":
                    return "8393";
                case "ヴ":
                    return "8394";
                case "ヵ":
                    return "8395";
                case "ヶ":
                    return "8396";
                case "中":
                    return "9286";
                case "習":
                    return "8f4b";
                case "練":
                    return "97fb";
                case "試":
                    return "8e8e";
                case "合":
                    return "8d87";
                case "接":
                    return "90da";
                case "続":
                    return "91b1";
                case "第":
                    return "91e6";
                case "一":
                    return "88ea";
                case "押":
                    return "899f";
                case "制":
                    return "90a7";
                case "服":
                    return "959e";
                case "春":
                    return "8f74";
                case "菜":
                    return "8dd8";
                case "夏":
                    return "89c4";
                case "谷":
                    return "924a";
                case "冬":
                    return "937e";
                case "花":
                    return "89d4";
                case "響":
                    return "8bbf";
                case "正":
                    return "90b3";
                case "剛":
                    return "8d84";
                case "久":
                    return "8b76";
                case "也":
                    return "96e7";
                case "吉":
                    return "8b67";
                case "良":
                    return "97c7";
                case "瞳":
                    return "93b5";
                case "真":
                    return "905e";
                case "日":
                    return "93fa";
                case "茜":
                    return "88a9";
                case "水":
                    return "9085";
                case "鳥":
                    return "92b9";
                case "専":
                    return "90ea";
                case "白":
                    return "9492";
                case "恋":
                    return "97f6";
                case "雲":
                    return "895f";
                case "．":
                    return "8144";
                case "幻":
                    return "8cb6";
                case "影":
                    return "8965";
                case "聖":
                    return "90b9";
                case "万":
                    return "969c";
                case "能":
                    return "945c";
                case "坂":
                    return "8de2";
                case "天":
                    return "9356";
                case "原":
                    return "8cb4";
                case "海":
                    return "8a43";
                case "月":
                    return "8c8e";
                case "光":
                    return "8cf5";
                case "御":
                    return "8ce4";
                case "農":
                    return "945f";
                case "戸":
                    return "8ccb";
                case "清":
                    return "90b4";
                case "修":
                    return "8f43";
                case "秋":
                    return "8f48";
                case "旧":
                    return "8b8c";
                case "土":
                    return "9379";
                case "星":
                    return "90af";
                case "徒":
                    return "936b";
                case "伝":
                    return "9360";
                case "地":
                    return "926e";
                case "広":
                    return "8d4c";
                case "孔":
                    return "8d45";
                case "‐":
                    return "815d";
                case "☆":
                    return "8199";
                case "基":
                    return "8aee";
                case "的":
                    return "9349";
                case "陣":
                    return "9077";
                case "形":
                    return "8c60";
                case "置":
                    return "9275";
                case "重":
                    return "8f64";
                case "視":
                    return "8e8b";
                case "司":
                    return "8e69";
                case "令":
                    return "97df";
                case "塔":
                    return "9383";
                case "除":
                    return "8f9c";
                case "解":
                    return "89f0";
                case "指":
                    return "8e77";
                case "揮":
                    return "8af6";
                case "応":
                    return "899e";
                case "援":
                    return "8987";
                case "仲":
                    return "9287";
                case "ゼ":
                    return "835b";
                case "二":
                    return "93f1";
                case "三":
                    return "8e4f";
                case "四":
                    return "8e6c";
                case "五":
                    return "8cdc";
                case "六":
                    return "985a";
                case "決":
                    return "8c88";
                case "勝":
                    return "8f9f";
                case "戦":
                    return "90ed";
                case "大":
                    return "91e5";
                case "会":
                    return "89ef";
                case "七":
                    return "8eb5";
                case "八":
                    return "94aa";
                case "九":
                    return "8be3";
                case "－":
                    return "817c";
                case "開":
                    return "8a4a";
                case "始":
                    return "8e6e";
                case "秒":
                    return "9562";
                case "：":
                    return "8146";
                case "数":
                    return "9094";
                case "必":
                    return "954b";
                case "殺":
                    return "8e45";
                case "技":
                    return "8b5a";
                case "回":
                    return "89f1";
                case "率":
                    return "97a6";
                case "支":
                    return "8e78";
                case "配":
                    return "947a";
                case "分":
                    return "95aa";
                case "設":
                    return "90dd";
                case "定":
                    return "92e8";
                case "挑":
                    return "92a7";
                case "再":
                    return "8dc4";
                case "特":
                    return "93c1";
                case "訓":
                    return "8c50";
                case "部":
                    return "9594";
                case "室":
                    return "8eba";
                case "模":
                    return "96cd";
                case "様":
                    return "976c";
                case "替":
                    return "91d6";
                case "初":
                    return "8f89";
                case "心":
                    return "9053";
                case "者":
                    return "8ed2";
                case "通":
                    return "92ca";
                case "常":
                    return "8fed";
                case "切":
                    return "90d8";
                case "相":
                    return "918a";
                case "手":
                    return "8ee8";
                case "難":
                    return "93ef";
                case "易":
                    return "88d5";
                case "度":
                    return "9378";
                case "下":
                    return "89ba";
                case "少":
                    return "8fad";
                case "入":
                    return "93fc";
                case "断":
                    return "9266";
                case "止":
                    return "8e7e";
                case "選":
                    return "9149";
                case "択":
                    return "91f0";
                case "人":
                    return "906c";
                case "確":
                    return "8a6d";
                case "認":
                    return "9446";
                case "操":
                    return "9180";
                case "作":
                    return "8dec";
                case "要":
                    return "9776";
                case "術":
                    return "8f70";
                case "変":
                    return "95cf";
                case "更":
                    return "8d58";
                case "準":
                    return "8f80";
                case "備":
                    return "94f5";
                case "化":
                    return "89bb";
                case "参":
                    return "8e51";
                case "加":
                    return "89c1";
                case "対":
                    return "91ce";
                case "遊":
                    return "9756";
                case "方":
                    return "95fb";
                case "見":
                    return "8ca9";
                case "読":
                    return "93c7";
                case "込":
                    return "8d9e";
                case "完":
                    return "8aae";
                case "了":
                    return "97b9";
                case "情":
                    return "8fee";
                case "報":
                    return "95f1";
                case "使":
                    return "8e67";
                case "用":
                    return "9770";
                case "控":
                    return "8d54";
                case "以":
                    return "88c8";
                case "上":
                    return "8fe3";
                case "効":
                    return "8cf8";
                case "果":
                    return "89ca";
                case "残":
                    return "8e63";
                case "／":
                    return "815e";
                case "名":
                    return "96bc";
                case "（":
                    return "8169";
                case "右":
                    return "8945";
                case "）":
                    return "816a";
                case "左":
                    return "8db6";
                case "外":
                    return "8a4f";
                case "最":
                    return "8dc5";
                case "低":
                    return "92e1";
                case "間":
                    return "8ad4";
                case "復":
                    return "959c";
                case "威":
                    return "88d0";
                case "力":
                    return "97cd";
                case "全":
                    return "9153";
                case "体":
                    return "91cc";
                case "移":
                    return "88da";
                case "動":
                    return "93ae";
                case "攻":
                    return "8d55";
                case "撃":
                    return "8c82";
                case "守":
                    return "8ee7";
                case "示":
                    return "8ea6";
                case "時":
                    return "8e9e";
                case "新":
                    return "9056";
                case "成":
                    return "90ac";
                case "削":
                    return "8ded";
                case "前":
                    return "914f";
                case "実":
                    return "8ec0";
                case "況":
                    return "8bb5";
                case "箱":
                    return "94a0";
                case "編":
                    return "95d2";
                case "遠":
                    return "8993";
                case "征":
                    return "90aa";
                case "行":
                    return "8d73";
                case "背":
                    return "9477";
                case "番":
                    return "94d4";
                case "号":
                    return "8d86";
                case "所":
                    return "8f8a";
                case "持":
                    return "8e9d";
                case "購":
                    return "8d77";
                case "同":
                    return "93af";
                case "足":
                    return "91ab";
                case "監":
                    return "8ac4";
                case "督":
                    return "93c2";
                case "買":
                    return "9483";
                case "愛":
                    return "88a4";
                case "称":
                    return "8fcc";
                case "並":
                    return "95c0";
                case "多":
                    return "91bd";
                case "属":
                    return "91ae";
                case "性":
                    return "90ab";
                case "調":
                    return "92b2";
                case "子":
                    return "8e71";
                case "総":
                    return "918d";
                case "得":
                    return "93be";
                case "点":
                    return "935f";
                case "値":
                    return "926c";
                case "出":
                    return "8f6f";
                case "場":
                    return "8fea";
                case "種":
                    return "8eed";
                case "類":
                    return "97de";
                case "装":
                    return "9195";
                case "％":
                    return "8193";
                case "発":
                    return "94ad";
                case "険":
                    return "8caf";
                case "悪":
                    return "88ab";
                case "漂":
                    return "9559";
                case "楽":
                    return "8a79";
                case "疲":
                    return "94e6";
                case "話":
                    return "9862";
                case "聞":
                    return "95b7";
                case "活":
                    return "8a88";
                case "躍":
                    return "96f4";
                case "落":
                    return "978e";
                case "喜":
                    return "8aec";
                case "優":
                    return "9744";
                case "迷":
                    return "96c0";
                case "困":
                    return "8da2";
                case "興":
                    return "8bbb";
                case "味":
                    return "96a1";
                case "悔":
                    return "89f7";
                case "食":
                    return "9048";
                case "熱":
                    return "944d";
                case "説":
                    return "90e0";
                case "明":
                    return "96be";
                case "個":
                    return "8cc2";
                case "績":
                    return "90d1";
                case "管":
                    return "8ac7";
                case "理":
                    return "979d";
                case "握":
                    return "88ac";
                case "嬉":
                    return "8af0";
                case "未":
                    return "96a2";
                case "【":
                    return "8179";
                case "】":
                    return "817a";
                case "強":
                    return "8bad";
                case "書":
                    return "8f91";
                case "倒":
                    return "937c";
                case "自":
                    return "8ea9";
                case "河":
                    return "89cd";
                case "川":
                    return "90ec";
                case "敷":
                    return "957e";
                case "協":
                    return "8ba6";
                case "連":
                    return "9841";
                case "目":
                    return "96da";
                case "競":
                    return "8ba3";
                case "音":
                    return "89b9";
                case "量":
                    return "97ca";
                case "振":
                    return "9055";
                case "内":
                    return "93e0";
                case "容":
                    return "9765";
                case "済":
                    return "8dcf";
                case "亀":
                    return "8b54";
                case "崎":
                    return "8de8";
                case "童":
                    return "93b6";
                case "牙":
                    return "89e5";
                case "山":
                    return "8e52";
                case "道":
                    return "93b9";
                case "条":
                    return "8ff0";
                case "木":
                    return "96d8";
                case "暮":
                    return "95e9";
                case "夕":
                    return "975b";
                case "弥":
                    return "96ed";
                case "吹":
                    return "9081";
                case "雪":
                    return "90e1";
                case "士":
                    return "8e6d";
                case "郎":
                    return "9859";
                case "鬼":
                    return "8b53";
                case "有":
                    return "974c";
                case "風":
                    return "9597";
                case "丸":
                    return "8adb";
                case "太":
                    return "91be";
                case "不":
                    return "9573";
                case "王":
                    return "89a4";
                case "壁":
                    return "95c7";
                case "塀":
                    return "95bb";
                case "円":
                    return "897e";
                case "堂":
                    return "93b0";
                case "終":
                    return "8f49";
                case "奪":
                    return "9244";
                case "紹":
                    return "8fd0";
                case "介":
                    return "89ee";
                case "関":
                    return "8ad6";
                case "係":
                    return "8c57";
                case "無":
                    return "96b3";
                case "信":
                    return "904d";
                case "本":
                    return "967b";
                case "保":
                    return "95db";
                case "存":
                    return "91b6";
                case "画":
                    return "89e6";
                case "面":
                    return "96ca";
                case "空":
                    return "8bf3";
                case "消":
                    return "8fc1";
                case "去":
                    return "8b8e";
                case "意":
                    return "88d3";
                case "壊":
                    return "89f3";
                case "失":
                    return "8eb8";
                case "敗":
                    return "9473";
                case "拡":
                    return "8a67";
                case "張":
                    return "92a3";
                case "抜":
                    return "94b2";
                case "差":
                    return "8db7";
                case "現":
                    return "8cbb";
                case "在":
                    return "8ddd";
                case "他":
                    return "91bc";
                case "生":
                    return "90b6";
                case "取":
                    return "8ee6";
                case "扱":
                    return "88b5";
                case "繋":
                    return "8c71";
                case "先":
                    return "90e6";
                case "元":
                    return "8cb3";
                case "戻":
                    return "96df";
                case "当":
                    return "9396";
                case "典":
                    return "9354";
                case "費":
                    return "94ef";
                case "各":
                    return "8a65";
                case "追":
                    return "92c7";
                case "両":
                    return "97bc";
                case "秘":
                    return "94e9";
                case "訣":
                    return "8c8d";
                case "次":
                    return "8e9f";
                case "起":
                    return "8b4e";
                case "＋":
                    return "817b";
                case "＿":
                    return "8151";
                case "＆":
                    return "8195";
                case "組":
                    return "9167";
                case "廃":
                    return "9470";
                case "棄":
                    return "8afc";
                case "世":
                    return "90a2";
                case "界":
                    return "8a45";
                case "改":
                    return "89fc";
                case "雷":
                    return "978b";
                case "門":
                    return "96e5";
                case "帝":
                    return "92e9";
                case "国":
                    return "8d91";
                case "学":
                    return "8a77";
                case "園":
                    return "8980";
                case "代":
                    return "91e3";
                case "表":
                    return "955c";
                case "韓":
                    return "8ad8";
                case "宇":
                    return "8946";
                case "革":
                    return "8a76";
                case "命":
                    return "96bd";
                case "女":
                    return "8f97";
                case "盤":
                    return "94d5";
                case "厚":
                    return "8cfa";
                case "鉄":
                    return "9353";
                case "誇":
                    return "8cd6";
                case "央":
                    return "899b";
                case "集":
                    return "8f57";
                case "型":
                    return "8c5e";
                case "則":
                    return "91a5";
                case "印":
                    return "88f3";
                case "象":
                    return "8fdb";
                case "突":
                    return "93cb";
                case "破":
                    return "946a";
                case "超":
                    return "92b4";
                case "謀":
                    return "9664";
                case "隙":
                    return "8c84";
                case "整":
                    return "90ae";
                case "然":
                    return "9152";
                case "波":
                    return "9467";
                case "状":
                    return "8ff3";
                case "繰":
                    return "8c4a";
                case "堅":
                    return "8c98";
                case "鋭":
                    return "8973";
                case "鍵":
                    return "8cae";
                case "飛":
                    return "94f2";
                case "蹴":
                    return "8f52";
                case "返":
                    return "95d4";
                case "砂":
                    return "8dbb";
                case "滑":
                    return "8a8a";
                case "丼":
                    return "98a5";
                case "尽":
                    return "9073";
                case "竜":
                    return "97b3";
                case "巻":
                    return "8aaa";
                case "＜":
                    return "8183";
                case "＞":
                    return "8184";
                case "打":
                    return "91c5";
                case "狙":
                    return "915f";
                case "計":
                    return "8c76";
                case "金":
                    return "8be0";
                case "高":
                    return "8d82";
                case "激":
                    return "8c83";
                case "辛":
                    return "9068";
                case "気":
                    return "8b43";
                case "極":
                    return "8bc9";
                case "馬":
                    return "946e";
                case "■":
                    return "81a1";
                case "杯":
                    return "9474";
                case "進":
                    return "9069";
                case "早":
                    return "9181";
                case "弱":
                    return "8ee3";
                case "猛":
                    return "96d2";
                case "走":
                    return "9196";
                case "近":
                    return "8bdf";
                case "血":
                    return "8c8c";
                case "疾":
                    return "8ebe";
                case "談":
                    return "926b";
                case "虫":
                    return "928e";
                case "年":
                    return "944e";
                case "感":
                    return "8ab4";
                case "欲":
                    return "977e";
                case "思":
                    return "8e76";
                case "負":
                    return "9589";
                case "言":
                    return "8cbe";
                case "徴":
                    return "92a5";
                case "身":
                    return "9067";
                case "格":
                    return "8a69";
                case "器":
                    return "8aed";
                case "炎":
                    return "898a";
                case "才":
                    return "8dcb";
                case "想":
                    return "917a";
                case "陰":
                    return "8941";
                case "努":
                    return "9377";
                case "知":
                    return "926d";
                case "識":
                    return "8eaf";
                case "腕":
                    return "9872";
                case "軽":
                    return "8c79";
                case "呼":
                    return "8cc4";
                case "魔":
                    return "9682";
                case "師":
                    return "8e74";
                case "彼":
                    return "94de";
                case "事":
                    return "8e96";
                case "件":
                    return "8c8f";
                case "倍":
                    return "947b";
                case "品":
                    return "9569";
                case "男":
                    return "926a";
                case "乗":
                    return "8fe6";
                case "小":
                    return "8fac";
                case "覚":
                    return "8a6f";
                case "亡":
                    return "9653";
                case "弟":
                    return "92ed";
                case "異":
                    return "88d9";
                case "孤":
                    return "8cc7";
                case "反":
                    return "94bd";
                case "逆":
                    return "8b74";
                case "児":
                    return "8e99";
                case "周":
                    return "8efc";
                case "彗":
                    return "9c61";
                case "豪":
                    return "8d8b";
                case "寺":
                    return "8e9b";
                case "潜":
                    return "90f6";
                case "南":
                    return "93ec";
                case "快":
                    return "89f5";
                case "好":
                    return "8d44";
                case "役":
                    return "96f0";
                case "巨":
                    return "8b90";
                case "静":
                    return "90c3";
                case "狂":
                    return "8bb6";
                case "犬":
                    return "8ca2";
                case "段":
                    return "9269";
                case "経":
                    return "8c6f";
                case "歴":
                    return "97f0";
                case "駆":
                    return "8bec";
                case "暴":
                    return "965c";
                case "頭":
                    return "93aa";
                case "転":
                    return "935d";
                case "速":
                    return "91ac";
                case "裏":
                    return "97a0";
                case "長":
                    return "92b7";
                case "武":
                    return "9590";
                case "姿":
                    return "8e70";
                case "神":
                    return "905f";
                case "冷":
                    return "97e2";
                case "酷":
                    return "8d93";
                case "噴":
                    return "95ac";
                case "火":
                    return "89ce";
                case "弓":
                    return "8b7c";
                case "射":
                    return "8ecb";
                case "矢":
                    return "96ee";
                case "放":
                    return "95fa";
                case "算":
                    return "8e5a";
                case "脳":
                    return "945d";
                case "略":
                    return "97aa";
                case "恵":
                    return "8c62";
                case "芸":
                    return "8c7c";
                case "美":
                    return "94fc";
                case "敵":
                    return "9347";
                case "立":
                    return "97a7";
                case "許":
                    return "8b96";
                case "凶":
                    return "8ba5";
                case "考":
                    return "8d6c";
                case "悟":
                    return "8ce5";
                case "着":
                    return "9285";
                case "物":
                    return "95a8";
                case "笑":
                    return "8fce";
                case "顔":
                    return "8ae7";
                case "葉":
                    return "9774";
                case "声":
                    return "90ba";
                case "乱":
                    return "9790";
                case "仮":
                    return "89bc";
                case "幼":
                    return "9763";
                case "昔":
                    return "90cc";
                case "病":
                    return "9561";
                case "灼":
                    return "8edc";
                case "徹":
                    return "934f";
                case "凍":
                    return "9380";
                case "暗":
                    return "88c3";
                case "奥":
                    return "899c";
                case "誰":
                    return "924e";
                case "跳":
                    return "92b5";
                case "闘":
                    return "93ac";
                case "混":
                    return "8dac";
                case "寝":
                    return "9051";
                case "勉":
                    return "95d7";
                case "災":
                    return "8dd0";
                case "予":
                    return "975c";
                case "測":
                    return "91aa";
                case "妹":
                    return "9685";
                case "兄":
                    return "8c5a";
                case "資":
                    return "8e91";
                case "死":
                    return "8e80";
                case "角":
                    return "8a70";
                case "向":
                    return "8cfc";
                case "忍":
                    return "9445";
                case "求":
                    return "8b81";
                case "絶":
                    return "90e2";
                case "危":
                    return "8aeb";
                case "引":
                    return "88f8";
                case "家":
                    return "89c6";
                case "息":
                    return "91a7";
                case "朝":
                    return "92a9";
                case "牛":
                    return "8b8d";
                case "霊":
                    return "97ec";
                case "受":
                    return "8ef3";
                case "秀":
                    return "8f47";
                case "今":
                    return "8da1";
                case "閉":
                    return "95c2";
                case "邪":
                    return "8ed7";
                case "匹":
                    return "9543";
                case "怒":
                    return "937b";
                case "軍":
                    return "8c52";
                case "団":
                    return "9263";
                case "魂":
                    return "8db0";
                case "姉":
                    return "8e6f";
                case "青":
                    return "90c2";
                case "眠":
                    return "96b0";
                case "串":
                    return "8bf8";
                case "店":
                    return "9358";
                case "娘":
                    return "96ba";
                case "禁":
                    return "8bd6";
                case "隠":
                    return "8942";
                case "護":
                    return "8cec";
                case "華":
                    return "89d8";
                case "麗":
                    return "97ed";
                case "流":
                    return "97ac";
                case "泣":
                    return "8b83";
                case "将":
                    return "8fab";
                case "母":
                    return "95ea";
                case "居":
                    return "8b8f";
                case "酒":
                    return "8ef0";
                case "屋":
                    return "89ae";
                case "親":
                    return "9065";
                case "野":
                    return "96ec";
                case "球":
                    return "8b85";
                case "貝":
                    return "8a4c";
                case "積":
                    return "90cf";
                case "庭":
                    return "92eb";
                case "阪":
                    return "8de3";
                case "社":
                    return "8ed0";
                case "過":
                    return "89df";
                case "兵":
                    return "95ba";
                case "教":
                    return "8bb3";
                case "非":
                    return "94f1";
                case "荒":
                    return "8d72";
                case "々":
                    return "8158";
                case "圧":
                    return "88b3";
                case "石":
                    return "90ce";
                case "限":
                    return "8cc0";
                case "髪":
                    return "94af";
                case "深":
                    return "905b";
                case "闇":
                    return "88c5";
                case "途":
                    return "9372";
                case "利":
                    return "9798";
                case "之":
                    return "9456";
                case "瀬":
                    return "90a3";
                case "黒":
                    return "8d95";
                case "田":
                    return "9363";
                case "舎":
                    return "8ec9";
                case "可":
                    return "89c2";
                case "機":
                    return "8b40";
                case "賦":
                    return "958a";
                case "安":
                    return "88c0";
                case "貴":
                    return "8b4d";
                case "公":
                    return "8cf6";
                case "“":
                    return "8167";
                case "”":
                    return "8168";
                case "孫":
                    return "91b7";
                case "似":
                    return "8e97";
                case "字":
                    return "8e9a";
                case "交":
                    return "8cf0";
                case "聴":
                    return "92ae";
                case "曲":
                    return "8bc8";
                case "泳":
                    return "896a";
                case "浮":
                    return "9582";
                case "与":
                    return "975e";
                case "凌":
                    return "97bd";
                case "祖":
                    return "9163";
                case "父":
                    return "9583";
                case "軒":
                    return "8cac";
                case "主":
                    return "8ee5";
                case "惚":
                    return "8d9b";
                case "厳":
                    return "8cb5";
                case "後":
                    return "8ce3";
                case "任":
                    return "9443";
                case "観":
                    return "8acf";
                case "察":
                    return "8e40";
                case "員":
                    return "88f5";
                case "温":
                    return "89b7";
                case "収":
                    return "8efb";
                case "校":
                    return "8d5a";
                case "馴":
                    return "93e9";
                case "染":
                    return "90f5";
                case "嫌":
                    return "8c99";
                case "帥":
                    return "9083";
                case "輩":
                    return "9479";
                case "燃":
                    return "9452";
                case "爆":
                    return "949a";
                case "車":
                    return "8ed4";
                case "暇":
                    return "89c9";
                case "釣":
                    return "92de";
                case "俊":
                    return "8f72";
                case "囲":
                    return "88cd";
                case "態":
                    return "91d4";
                case "素":
                    return "9166";
                case "直":
                    return "92bc";
                case "業":
                    return "8bc6";
                case "帰":
                    return "8b41";
                case "達":
                    return "9242";
                case "構":
                    return "8d5c";
                case "劇":
                    return "8c80";
                case "抱":
                    return "95f8";
                case "尊":
                    return "91b8";
                case "敬":
                    return "8c68";
                case "析":
                    return "90cd";
                case "別":
                    return "95ca";
                case "甘":
                    return "8ac3";
                case "警":
                    return "8c78";
                case "官":
                    return "8aaf";
                case "織":
                    return "9044";
                case "夢":
                    return "96b2";
                case "料":
                    return "97bf";
                case "何":
                    return "89bd";
                case "賞":
                    return "8fdc";
                case "職":
                    return "9045";
                case "位":
                    return "88ca";
                case "族":
                    return "91b0";
                case "靴":
                    return "8c43";
                case "磨":
                    return "9681";
                case "遺":
                    return "88e2";
                case "跡":
                    return "90d5";
                case "掘":
                    return "8c40";
                case "隊":
                    return "91e0";
                case "兼":
                    return "8c93";
                case "北":
                    return "966b";
                case "屈":
                    return "8bfc";
                case "逸":
                    return "88ed";
                case "材":
                    return "8dde";
                case "肌":
                    return "94a7";
                case "疑":
                    return "8b5e";
                case "語":
                    return "8cea";
                case "怪":
                    return "89f6";
                case "双":
                    return "916f";
                case "柔":
                    return "8f5f";
                case "和":
                    return "9861";
                case "像":
                    return "919c";
                case "烈":
                    return "97f3";
                case "弾":
                    return "9265";
                case "炭":
                    return "9259";
                case "墨":
                    return "966e";
                case "絵":
                    return "8a47";
                case "描":
                    return "9560";
                case "琴":
                    return "8bd5";
                case "百":
                    return "9553";
                case "登":
                    return "936f";
                case "頂":
                    return "92b8";
                case "根":
                    return "8daa";
                case "島":
                    return "9387";
                case "住":
                    return "8f5a";
                case "判":
                    return "94bb";
                case "商":
                    return "8fa4";
                case "勤":
                    return "8bce";
                case "傍":
                    return "9654";
                case "施":
                    return "8e7b";
                case "務":
                    return "96b1";
                case "老":
                    return "9856";
                case "齢":
                    return "97ee";
                case "恐":
                    return "8bb0";
                case "来":
                    return "9788";
                case "共":
                    return "8ba4";
                case "供":
                    return "8b9f";
                case "頃":
                    return "8da0";
                case "故":
                    return "8ccc";
                case "剣":
                    return "8c95";
                case "城":
                    return "8fe9";
                case "京":
                    return "8b9e";
                case "育":
                    return "88e7";
                case "口":
                    return "8cfb";
                case "尾":
                    return "94f6";
                case "豆":
                    return "93a4";
                case "腐":
                    return "9585";
                case "色":
                    return "9046";
                case "違":
                    return "88e1";
                case "皇":
                    return "8d63";
                case "忠":
                    return "9289";
                case "筋":
                    return "8bd8";
                case "肉":
                    return "93f7";
                case "鍛":
                    return "9262";
                case "胸":
                    return "8bb9";
                case "吸":
                    return "8b7a";
                case "舞":
                    return "9591";
                case "憧":
                    return "93b2";
                case "路":
                    return "9848";
                case "塞":
                    return "8dc7";
                case "惜":
                    return "90c9";
                case "柄":
                    return "95bf";
                case "趣":
                    return "8eef";
                case "掃":
                    return "917c";
                case "謎":
                    return "93e4";
                case "満":
                    return "969e";
                case "遂":
                    return "908b";
                case "誠":
                    return "90bd";
                case "割":
                    return "8a84";
                case "固":
                    return "8cc5";
                case "庫":
                    return "8cc9";
                case "逃":
                    return "93a6";
                case "運":
                    return "895e";
                case "申":
                    return "905c";
                case "送":
                    return "9197";
                case "奇":
                    return "8aef";
                case "策":
                    return "8df4";
                case "注":
                    return "928d";
                case "価":
                    return "89bf";
                case "彦":
                    return "9546";
                case "記":
                    return "8b4c";
                case "録":
                    return "985e";
                case "派":
                    return "9468";
                case "客":
                    return "8b71";
                case "餌":
                    return "8961";
                case "付":
                    return "9574";
                case "脅":
                    return "8bba";
                case "退":
                    return "91de";
                case "刺":
                    return "8e68";
                case "巧":
                    return "8d49";
                case "惑":
                    return "9866";
                case "刃":
                    return "906e";
                case "沈":
                    return "92be";
                case "腰":
                    return "8d98";
                case "眼":
                    return "8ae1";
                case "志":
                    return "8e75";
                case "礼":
                    return "97e7";
                case "儀":
                    return "8b56";
                case "篠":
                    return "8ec2";
                case "牢":
                    return "9853";
                case "獄":
                    return "8d96";
                case "脱":
                    return "9245";
                case "級":
                    return "8b89";
                case "俺":
                    return "89b4";
                case "防":
                    return "9668";
                case "羅":
                    return "9785";
                case "争":
                    return "9188";
                case "毎":
                    return "9688";
                case "怖":
                    return "957c";
                case "虐":
                    return "8b73";
                case "悲":
                    return "94df";
                case "慕":
                    return "95e7";
                case "課":
                    return "89db";
                case "環":
                    return "8ac2";
                case "境":
                    return "8bab";
                case "奴":
                    return "937a";
                case "丈":
                    return "8fe4";
                case "夫":
                    return "9576";
                case "散":
                    return "8e55";
                case "魅":
                    return "96a3";
                case "貌":
                    return "9665";
                case "香":
                    return "8d81";
                case "寡":
                    return "89c7";
                case "黙":
                    return "96d9";
                case "雄":
                    return "9759";
                case "弁":
                    return "95d9";
                case "匂":
                    return "93f5";
                case "千":
                    return "90e7";
                case "宮":
                    return "8b7b";
                case "掌":
                    return "8fb6";
                case "併":
                    return "95b9";
                case "×":
                    return "817e";
                case "松":
                    return "8fbc";
                case "拓":
                    return "91f1";
                case "斗":
                    return "936c";
                case "霧":
                    return "96b6";
                case "蘭":
                    return "9796";
                case "雨":
                    return "894a";
                case "陽":
                    return "977a";
                case "諸":
                    return "8f94";
                case "葛":
                    return "8a8b";
                case "亮":
                    return "97ba";
                case "西":
                    return "90bc";
                case "助":
                    return "8f95";
                case "劉":
                    return "97ab";
                case "錦":
                    return "8bd1";
                case "龍":
                    return "97b4";
                case "沖":
                    return "89ab";
                case "黄":
                    return "89a9";
                case "曹":
                    return "9182";
                case "苦":
                    return "8bea";
                case "造":
                    return "91a2";
                case "適":
                    return "934b";
                case "伸":
                    return "904c";
                case "悩":
                    return "9459";
                case "己":
                    return "8cc8";
                case "欠":
                    return "8c87";
                case "評":
                    return "955d";
                case "亜":
                    return "889f";
                case "炉":
                    return "9846";
                case "照":
                    return "8fc6";
                case "財":
                    return "8de0";
                case "閥":
                    return "94b4";
                case "若":
                    return "8ee1";
                case "輝":
                    return "8b50";
                case "増":
                    return "919d";
                case "友":
                    return "9746";
                case "采":
                    return "8dd1";
                case "奮":
                    return "95b1";
                case "束":
                    return "91a9";
                case "～":
                    return "8160";
                case "半":
                    return "94bc";
                case "栄":
                    return "8968";
                case "養":
                    return "977b";
                case "議":
                    return "8b63";
                case "由":
                    return "9752";
                case "私":
                    return "8e84";
                case "催":
                    return "8dc3";
                case "究":
                    return "8b86";
                case "結":
                    return "8c8b";
                case "油":
                    return "96fb";
                case "願":
                    return "8ae8";
                case "標":
                    return "9557";
                case "験":
                    return "8cb1";
                case "符":
                    return "9584";
                case "渡":
                    return "936e";
                case "勢":
                    return "90a8";
                case "緒":
                    return "8f8f";
                case "念":
                    return "944f";
                case "『":
                    return "8177";
                case "』":
                    return "8178";
                case "季":
                    return "8b47";
                case "節":
                    return "90df";
                case "獲":
                    return "8a6c";
                case "飾":
                    return "8ffc";
                case "期":
                    return "8afa";
                case "待":
                    return "91d2";
                case "簡":
                    return "8ac8";
                case "単":
                    return "9250";
                case "肩":
                    return "8ca8";
                case "仕":
                    return "8e64";
                case "休":
                    return "8b78";
                case "雰":
                    return "95b5";
                case "←":
                    return "81a9";
                case "→":
                    return "81a8";
                case "扉":
                    return "94e0";
                case "宝":
                    return "95f3";
                case "投":
                    return "938a";
                case "精":
                    return "90b8";
                case "紅":
                    return "8d67";
                case "蓮":
                    return "9840";
                case "焼":
                    return "8fc4";
                case "証":
                    return "8fd8";
                case "互":
                    return "8cdd";
                case "僕":
                    return "966c";
                case "我":
                    return "89e4";
                case "程":
                    return "92f6";
                case "越":
                    return "897a";
                case "掴":
                    return "92cd";
                case "叩":
                    return "9240";
                case "叫":
                    return "8ba9";
                case "望":
                    return "965d";
                case "急":
                    return "8b7d";
                case "損":
                    return "91b9";
                case "吐":
                    return "9366";
                case "溢":
                    return "88ec";
                case "♪":
                    return "81f4";
                case "吠":
                    return "9669";
                case "捻":
                    return "9450";
                case "潰":
                    return "92d7";
                case "醜":
                    return "8f58";
                case "抗":
                    return "8d52";
                case "芝":
                    return "8ec5";
                case "嗅":
                    return "9a6b";
                case "希":
                    return "8af3";
                case "頑":
                    return "8ae6";
                case "貰":
                    return "96e1";
                case "頼":
                    return "978a";
                case "導":
                    return "93b1";
                case "答":
                    return "939a";
                case "懸":
                    return "8c9c";
                case "寄":
                    return "8af1";
                case "君":
                    return "8c4e";
                case "細":
                    return "8dd7";
                case "氷":
                    return "9558";
                case "宙":
                    return "9288";
                case "侵":
                    return "904e";
                case "酔":
                    return "908c";
                case "誕":
                    return "9261";
                case "冒":
                    return "9660";
                case "探":
                    return "9254";
                case "詰":
                    return "8b6c";
                case "鹿":
                    return "8ead";
                case "甲":
                    return "8d62";
                case "斐":
                    return "94e3";
                case "憩":
                    return "8c65";
                case "題":
                    return "91e8";
                case "台":
                    return "91e4";
                case "詞":
                    return "8e8c";
                case "週":
                    return "8f54";
                case "降":
                    return "8d7e";
                case "①":
                    return "8740";
                case "②":
                    return "8741";
                case "③":
                    return "8742";
                case "④":
                    return "8743";
                case "⑤":
                    return "8744";
                case "⑥":
                    return "8745";
                case "⑦":
                    return "8746";
                case "⑧":
                    return "8747";
                case "⑨":
                    return "8748";
                case "⑩":
                    return "8749";
                case "⑪":
                    return "874A";
                case "⑫":
                    return "874B";
                case "⑬":
                    return "874C";
                case "⑭":
                    return "874D";
                case "⑮":
                    return "874E";
                case "⑯":
                    return "874F";
                case "⑰":
                    return "8750";
                case "⑱":
                    return "8751";
                case "⑲":
                    return "8752";
                case "⑳":
                    return "8753";
                case "即":
                    return "91a6";
                case "席":
                    return "90c8";
                case "誓":
                    return "90be";
                case "擁":
                    return "9769";
                case "統":
                    return "939d";
                case "融":
                    return "975a";
                case "沌":
                    return "93d7";
                case "乙":
                    return "89b3";
                case "継":
                    return "8c70";
                case "封":
                    return "9595";
                case "勇":
                    return "9745";
                case "赤":
                    return "90d4";
                case "騎":
                    return "8b52";
                case "洗":
                    return "90f4";
                case "縦":
                    return "8f63";
                case "專":
                    return "9b93";
                case "飲":
                    return "88f9";
                case "涛":
                    return "9393";
                case "町":
                    return "92ac";
                case "湯":
                    return "9392";
                case "旅":
                    return "97b7";
                case "留":
                    return "97af";
                case "幅":
                    return "959d";
                case "順":
                    return "8f87";
                case "慢":
                    return "969d";
                case "里":
                    return "97a2";
                case "演":
                    return "8989";
                case "林":
                    return "97d1";
                case "吾":
                    return "8ce1";
                case "仁":
                    return "906d";
                case "栗":
                    return "8c49";
                case "平":
                    return "95bd";
                case "歩":
                    return "95e0";
                case "宍":
                    return "8eb3";
                case "佐":
                    return "8db2";
                case "岡":
                    return "89aa";
                case "哉":
                    return "8dc6";
                case "綱":
                    return "8d6a";
                case "浦":
                    return "8959";
                case "鷹":
                    return "91e9";
                case "都":
                    return "9373";
                case "虎":
                    return "8cd5";
                case "電":
                    return "9364";
                case "緑":
                    return "97ce";
                case "源":
                    return "8cb9";
                case "幸":
                    return "8d4b";
                case "健":
                    return "8c92";
                case "辺":
                    return "95d3";
                case "咲":
                    return "8de7";
                case "洞":
                    return "93b4";
                case "呑":
                    return "93db";
                case "阿":
                    return "88a2";
                case "露":
                    return "9849";
                case "灰":
                    return "8a44";
                case "須":
                    return "907b";
                case "魚":
                    return "8b9b";
                case "智":
                    return "9271";
                case "豊":
                    return "964c";
                case "貞":
                    return "92e5";
                case "沼":
                    return "8fc0";
                case "治":
                    return "8ea1";
                case "蟹":
                    return "8a49";
                case "玲":
                    return "97e6";
                case "藤":
                    return "93a1";
                case "論":
                    return "985f";
                case "紀":
                    return "8b49";
                case "伊":
                    return "88c9";
                case "布":
                    return "957a";
                case "井":
                    return "88e4";
                case "畿":
                    return "8b45";
                case "岩":
                    return "8ae2";
                case "蔵":
                    return "91a0";
                case "寒":
                    return "8aa6";
                case "薔":
                    return "e54b";
                case "薇":
                    return "e54e";
                case "倉":
                    return "9171";
                case "掛":
                    return "8a7c";
                case "茂":
                    return "96ce";
                case "晴":
                    return "90b0";
                case "涼":
                    return "97c1";
                case "杉":
                    return "9099";
                case "森":
                    return "9058";
                case "垣":
                    return "8a5f";
                case "郷":
                    return "8bbd";
                case "院":
                    return "8940";
                case "幽":
                    return "9748";
                case "博":
                    return "948e";
                case "鶴":
                    return "92df";
                case "隆":
                    return "97b2";
                case "牧":
                    return "9671";
                case "寛":
                    return "8ab0";
                case "珠":
                    return "8eec";
                case "堀":
                    return "9678";
                case "津":
                    return "92c3";
                case "奈":
                    return "93de";
                case "館":
                    return "8ad9";
                case "如":
                    return "9440";
                case "州":
                    return "8f42";
                case "浜":
                    return "956c";
                case "梨":
                    return "979c";
                case "紺":
                    return "8dae";
                case "摩":
                    return "9680";
                case "村":
                    return "91ba";
                case "圭":
                    return "8c5c";
                case "沢":
                    return "91f2";
                case "篤":
                    return "93c4";
                case "狩":
                    return "8eeb";
                case "葵":
                    return "88a8";
                case "浪":
                    return "9851";
                case "豹":
                    return "955e";
                case "蛇":
                    return "8ed6";
                case "江":
                    return "8d5d";
                case "塚":
                    return "92cb";
                case "銅":
                    return "93ba";
                case "功":
                    return "8cf7";
                case "悠":
                    return "9749";
                case "譲":
                    return "8ff7";
                case "稲":
                    return "88ee";
                case "裂":
                    return "97f4";
                case "帆":
                    return "94bf";
                case "銀":
                    return "8be2";
                case "滝":
                    return "91ea";
                case "雅":
                    return "89eb";
                case "瀧":
                    return "91eb";
                case "隼":
                    return "94b9";
                case "英":
                    return "8970";
                case "湾":
                    return "9870";
                case "夜":
                    return "96e9";
                case "桜":
                    return "8df7";
                case "磯":
                    return "88e9";
                case "研":
                    return "8ca4";
                case "乃":
                    return "9454";
                case "図":
                    return "907d";
                case "鑑":
                    return "8ad3";
                case "請":
                    return "90bf";
                case "権":
                    return "8ca0";
                case "頻":
                    return "9570";
                case "詳":
                    return "8fda";
                case "覧":
                    return "9797";
                case "停":
                    return "92e2";
                case "既":
                    return "8af9";
                case "式":
                    return "8eae";
                case "°":
                    return "818b";
                case "揺":
                    return "9768";
                case "柱":
                    return "928c";
                case "貫":
                    return "8ad1";
                case "殊":
                    return "8eea";
                case "晶":
                    return "8fbb";
                case "毛":
                    return "96d1";
                case "嵐":
                    return "9792";
                case "拳":
                    return "8c9d";
                case "迫":
                    return "9497";
                case "史":
                    return "8e6a";
                case "離":
                    return "97a3";
                case "義":
                    return "8b60";
                case "携":
                    return "8c67";
                case "渦":
                    return "8951";
                case "獣":
                    return "8f62";
                case "翼":
                    return "9783";
                case "幕":
                    return "968b";
                case "誘":
                    return "9755";
                case "刀":
                    return "9381";
                case "閃":
                    return "914d";
                case "狼":
                    return "9854";
                case "憎":
                    return "919e";
                case "十":
                    return "8f5c";
                case "羽":
                    return "8948";
                case "槍":
                    return "9184";
                case "漆":
                    return "8ebd";
                case "為":
                    return "88d7";
                case "線":
                    return "90fc";
                case "罰":
                    return "94b1";
                case "包":
                    return "95ef";
                case "捕":
                    return "95df";
                case "絞":
                    return "8d69";
                case "古":
                    return "8cc3";
                case "召":
                    return "8fa2";
                case "喚":
                    return "8aab";
                case "殿":
                    return "9361";
                case "蘇":
                    return "9168";
                case "昇":
                    return "8fb8";
                case "奏":
                    return "9174";
                case "法":
                    return "9640";
                case "紋":
                    return "96e4";
                case "章":
                    return "8fcd";
                case "驚":
                    return "8bc1";
                case "砕":
                    return "8dd3";
                case "底":
                    return "92ea";
                case "斧":
                    return "9580";
                case "軌":
                    return "8b4f";
                case "払":
                    return "95a5";
                case "斬":
                    return "8e61";
                case "襲":
                    return "8f50";
                case "衝":
                    return "8fd5";
                case "建":
                    return "8c9a";
                case "築":
                    return "927a";
                case "旗":
                    return "8af8";
                case "穂":
                    return "95e4";
                case "触":
                    return "9047";
                case "磁":
                    return "8ea5";
                case "瞬":
                    return "8f75";
                case "綺":
                    return "e359";
                case "洋":
                    return "976d";
                case "坊":
                    return "9656";
                case "盛":
                    return "90b7";
                case "粉":
                    return "95b2";
                case "焦":
                    return "8fc5";
                case "錯":
                    return "8df6";
                case "肺":
                    return "9478";
                case "穴":
                    return "8c8a";
                case "巣":
                    return "9183";
                case "隅":
                    return "8bf7";
                case "鳴":
                    return "96c2";
                case "鼓":
                    return "8cdb";
                case "遅":
                    return "9278";
                case "質":
                    return "8ebf";
                case "潮":
                    return "92aa";
                case "擦":
                    return "8e43";
                case "爪":
                    return "92dc";
                case "鎌":
                    return "8a99";
                case "独":
                    return "93c6";
                case "寸":
                    return "90a1";
                case "致":
                    return "9276";
                case "列":
                    return "97f1";
                case "零":
                    return "97eb";
                case "銃":
                    return "8f65";
                case "群":
                    return "8c51";
                case "禄":
                    return "985c";
                case "脚":
                    return "8b72";
                case "含":
                    return "8adc";
                case "粒":
                    return "97b1";
                case "抽":
                    return "928a";
                case "額":
                    return "8a7a";
                case "菊":
                    return "8b65";
                case "凝":
                    return "8bc3";
                case "縮":
                    return "8f6b";
                case "揃":
                    return "91b5";
                case "虹":
                    return "93f8";
                case "帯":
                    return "91d1";
                case "規":
                    return "8b4b";
                case "蓄":
                    return "927e";
                case "滞":
                    return "91d8";
                case "片":
                    return "95d0";
                case "縄":
                    return "93ea";
                case "靭":
                    return "9078";
                case "這":
                    return "9487";
                case "翻":
                    return "967c";
                case "弄":
                    return "984d";
                case "凄":
                    return "90a6";
                case "複":
                    return "95a1";
                case "柵":
                    return "8df2";
                case "普":
                    return "9581";
                case "　":
                    return "8140";
                case "耳":
                    return "8ea8";
                case "傾":
                    return "8c58";
                case "短":
                    return "925a";
                case "充":
                    return "8f5b";
                case "該":
                    return "8a59";
                case "欄":
                    return "9793";
                case "項":
                    return "8d80";
                case "阻":
                    return "916a";
                case "等":
                    return "9399";
                case "範":
                    return "94cd";
                case "ё":
                    return "8476";
                default:
                    Console.WriteLine("Caractère introuvable: "+s);
                    return null;

            }
        }
    }
}
